"""Add missing fields to UserPref and Notification models

Revision ID: 02714c45e74e
Revises: 8294c8caaab3
Create Date: 2025-10-29 20:04:46.182404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02714c45e74e'
down_revision = '8294c8caaab3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketplace_accounts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('marketplace_accounts', 'account_username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('marketplace_accounts', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('my_items', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('notifications', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.alter_column('snap_jobs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user_prefs', sa.Column('saved_deals', sa.JSON(), nullable=False))
    op.add_column('user_prefs', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('user_prefs', sa.Column('search_radius_mi', sa.Integer(), nullable=False))
    op.add_column('user_prefs', sa.Column('notification_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_prefs', 'notification_enabled')
    op.drop_column('user_prefs', 'search_radius_mi')
    op.drop_column('user_prefs', 'location')
    op.drop_column('user_prefs', 'saved_deals')
    op.alter_column('snap_jobs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_column('notifications', 'user_id')
    op.alter_column('my_items', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('marketplace_accounts', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=True)
    op.alter_column('marketplace_accounts', 'account_username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('marketplace_accounts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
