"""add_price_analysis_table

Revision ID: 45d9553ae696
Revises: e7498d9b070a
Create Date: 2025-11-06 05:23:06.385664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d9553ae696'
down_revision = 'e7498d9b070a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
