"""Add last_synced_at field to MarketplaceAccount

Revision ID: 47aab62c1868
Revises: 02714c45e74e
Create Date: 2025-10-29 20:10:14.522463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47aab62c1868'
down_revision = '02714c45e74e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_accounts', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplace_accounts', 'last_synced_at')
    # ### end Alembic commands ###
