"""Add marketplace OAuth fields to MarketplaceAccount

Revision ID: 6b2c8f91d4a2
Revises: 47aab62c1868
Create Date: 2025-10-29 21:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2c8f91d4a2'
down_revision = '47aab62c1868'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add new columns for OAuth integration
    op.add_column('marketplace_accounts', sa.Column('marketplace', sa.String(50), nullable=True))
    op.add_column('marketplace_accounts', sa.Column('marketplace_account_id', sa.String(255), nullable=True))
    op.add_column('marketplace_accounts', sa.Column('access_token', sa.Text(), nullable=True))
    op.add_column('marketplace_accounts', sa.Column('refresh_token', sa.Text(), nullable=True))
    op.add_column('marketplace_accounts', sa.Column('connected_at', sa.DateTime(), nullable=True))

    # Create index on marketplace column for faster lookups
    op.create_index(op.f('ix_marketplace_accounts_marketplace'), 'marketplace_accounts', ['marketplace'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop index
    op.drop_index(op.f('ix_marketplace_accounts_marketplace'), table_name='marketplace_accounts')

    # Drop columns
    op.drop_column('marketplace_accounts', 'connected_at')
    op.drop_column('marketplace_accounts', 'refresh_token')
    op.drop_column('marketplace_accounts', 'access_token')
    op.drop_column('marketplace_accounts', 'marketplace_account_id')
    op.drop_column('marketplace_accounts', 'marketplace')

    # ### end Alembic commands ###
