"""add_price_analysis_table

Revision ID: 6f4529bf3003
Revises: 45d9553ae696
Create Date: 2025-11-06 19:51:32.613801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4529bf3003'
down_revision = '45d9553ae696'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
