"""Add user_id to SnapJob model

Revision ID: 8294c8caaab3
Revises: eaa0619d93ed
Create Date: 2025-10-29 19:57:26.254184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8294c8caaab3'
down_revision = 'eaa0619d93ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snap_jobs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_snap_jobs_user_id'), 'snap_jobs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'snap_jobs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'snap_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_snap_jobs_user_id'), table_name='snap_jobs')
    op.drop_column('snap_jobs', 'user_id')
    # ### end Alembic commands ###
