"""add_price_analysis_table

Revision ID: e3f605eb9c68
Revises: 6f4529bf3003
Create Date: 2025-11-06 19:52:39.261591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f605eb9c68'
down_revision = '6f4529bf3003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
