"""add_price_analysis_table

Revision ID: e7498d9b070a
Revises: add_meta_snapjob
Create Date: 2025-11-06 04:34:28.683473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7498d9b070a'
down_revision = 'add_meta_snapjob'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Drop dependent tables before their parents to avoid FK issues
    op.drop_index(op.f('ix_sales_orders_marketplace_listing_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_platform_name'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index(op.f('ix_marketplace_listings_platform_name'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_product_id'), table_name='marketplace_listings')
    op.drop_table('marketplace_listings')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_table('products')
    op.add_column('marketplace_accounts', sa.Column('marketplace', sa.String(length=50), nullable=False))
    op.alter_column('marketplace_accounts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('marketplace_accounts', 'account_username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_marketplace_accounts_platform'), table_name='marketplace_accounts')
    op.create_index(op.f('ix_marketplace_accounts_marketplace'), 'marketplace_accounts', ['marketplace'], unique=False)
    op.drop_column('marketplace_accounts', 'platform')
    op.add_column(
        'snap_jobs',
        sa.Column('metadata', sa.JSON(), nullable=False, server_default=sa.text("'{}'::json"))
    )
    op.alter_column('snap_jobs', 'metadata', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snap_jobs', 'metadata')
    op.add_column('marketplace_accounts', sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_marketplace_accounts_marketplace'), table_name='marketplace_accounts')
    op.create_index(op.f('ix_marketplace_accounts_platform'), 'marketplace_accounts', ['platform'], unique=False)
    op.alter_column('marketplace_accounts', 'account_username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('marketplace_accounts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('marketplace_accounts', 'marketplace')
    op.create_table('sales_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('marketplace_listing_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('sale_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('platform_fee_rate', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('shipping_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('net_profit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('sale_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['marketplace_listing_id'], ['marketplace_listings.id'], name=op.f('sales_orders_marketplace_listing_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sales_orders_pkey'))
    )
    op.create_index(op.f('ix_sales_orders_platform_name'), 'sales_orders', ['platform_name'], unique=False)
    op.create_index(op.f('ix_sales_orders_marketplace_listing_id'), 'sales_orders', ['marketplace_listing_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('products_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('original_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('base_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_inventory', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('internal_location', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('is_listed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='products_pkey'),
    sa.UniqueConstraint('sku', name='uq_products_sku', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_table('marketplace_listings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('platform_listing_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('platform_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('marketplace_listings_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('marketplace_listings_pkey')),
    sa.UniqueConstraint('platform_listing_id', name=op.f('uq_marketplace_listing_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_marketplace_listings_product_id'), 'marketplace_listings', ['product_id'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_platform_name'), 'marketplace_listings', ['platform_name'], unique=False)
    # ### end Alembic commands ###
