"""Add user_id and account fields to models

Revision ID: eaa0619d93ed
Revises: 001_initial_schema
Create Date: 2025-10-29 19:52:27.329867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa0619d93ed'
down_revision = '001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_accounts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('marketplace_accounts', sa.Column('account_username', sa.String(length=255), nullable=True))
    op.add_column('marketplace_accounts', sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'))
    op.create_index(op.f('ix_marketplace_accounts_user_id'), 'marketplace_accounts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'marketplace_accounts', 'users', ['user_id'], ['id'])
    op.add_column('my_items', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_my_items_user_id'), 'my_items', ['user_id'], unique=False)
    op.create_foreign_key(None, 'my_items', 'users', ['user_id'], ['id'])
    op.alter_column('user_prefs', 'user_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="user_id::integer")
    op.create_foreign_key(None, 'user_prefs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_prefs', type_='foreignkey')
    op.alter_column('user_prefs', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_constraint(None, 'my_items', type_='foreignkey')
    op.drop_index(op.f('ix_my_items_user_id'), table_name='my_items')
    op.drop_column('my_items', 'user_id')
    op.drop_constraint(None, 'marketplace_accounts', type_='foreignkey')
    op.drop_index(op.f('ix_marketplace_accounts_user_id'), table_name='marketplace_accounts')
    op.drop_column('marketplace_accounts', 'is_active')
    op.drop_column('marketplace_accounts', 'account_username')
    op.drop_column('marketplace_accounts', 'user_id')
    # ### end Alembic commands ###
